name: Admin Module
identifier: com.fustrate.admin
version: 1.0
author:
    name: Steven Hoffman
    email: fustrate@me.com
    website: http://www.fustrate.com/
description: |
    Admin module description

language_ns: admin
namespace: \smCore\Modules\Admin

routes:
    main:
        match: admin
        controller: Main
        method: main
    modules:
        match: admin/modules
        controller: Main
        method: modules

# Languages

    languages:
        match: admin/languages
        controller: Languages
        method: main
    viewLangPackage:
        match: "admin/languages/packages/:slug"
        controller: Languages
        method: viewPackage
    stringEdit:
        match: admin/languages/stringEdit
        controller: Languages
        method: stringEdit